/* This file is generated by arpcc, do not change manually! */
#ifndef __env_h__
#define __env_h__
#include "ProtocolWriter.h"
#include "ProtocolReader.h"
#include "EnumInfo.h"
//=============================================================
// enum Var
enum Var : S32
{
	V_None,
	V_WorldListenDB,
	V_WorldListenLogin,
	V_WorldListenGateway,
	V_WorldListenMall,
	V_GatewayListenClientMultiIndoor,
	V_MysqlHost,
	V_MysqlUser,
	V_MysqlPassword,
	V_DatabaseName,
	V_logersName,
	V_DebugLog,
	V_WorldListenGMT,
	V_WorldListenScene,
	V_WorldListenLogser,
	V_GMTListenWebServer,
	V_BacklogListen,
	V_UsedAnySDK,
	V_AnySDKOauthListen,
	V_AnySDKPayNotifyListen,
	V_CenterServerHost,
	V_LogServerHost,
	V_OpenServerTimestamp,
	V_IsNewServer,
	V_SMSUsername,
	V_SMSAuthToken,
	V_SMSAppId,
	V_SMSTmplateId,
	V_SMSTimeout,
	V_OpenRMBBack,
	V_GatewayHost,
	V_TestTaskSize,
	V_TestCaseSize,
	V_GM,
	V_Max,
};
extern EnumInfo enumVar;
#endif
